### ISSUE TITLE
Automatically deploy new versions of OSPO mind map to the website

### ISSUE THREAD

**Issue by tsteenbe** [todogroup/ospology#130]
Once a pull request updating the OSPO mind map is merged it should be automatically deployed to https://ospomindmap.todogroup.org/

**Comment by Siddhant-K-code** [comment]
Hey, I'm looking to contribute to this.
need more context on that - what is the current workflow of the release (any docs. avail.?) then I can create an automatic CI/CD pipeline for automatic release)

**Comment by mfix22** [comment]
https://github.com/todogroup/ospology/pull/179 partially addresses this, but there might be one more configuration we need to enable in the Netlify dashboard to enable production deployments from `main`. Happy to look into this, but I figure someone with permissions will want to instead once #179 merges. 🙂

**Comment by mfix22** [comment]
This should be fixed now with #179 🙌
