### ISSUE TITLE
OSPO mind map: education in two places

### ISSUE THREAD

**Issue by winterrocks** [todogroup/ospology#142]
At the moment in the mind map we have developer education in two places:

- Responsibilities - Oversee Open Source Compliance - **Educate Developers** - Training & Certification
- Responsibilities - Establish and Improve Open Source Policies and Processes - Processes - **Educating people**

These have a bit different flavors but are still close to each other and in order to make the mind map a tiny bit less complex, these two could be merged.

**Comment by tsteenbe** [comment]
@winterrocks  I did this so if people are solely focused on compliance side they would see all everything in 1 responsibility.

**Comment by winterrocks** [comment]
@tsteenbe makes sense. I guess that the mind map would get a bit too complicated if, e.g. on the Compliance branch there would be only Educate Developers and then a link to Establish and Improve Open Source Policies and Processes - Processes - Educating people, where we could move the Training & Certification that now lists the LFC courses. 
The mind map could end up being a graph that we do not want, because of the simplicity of mind maps.

**Comment by anajsana** [comment]
Is this solved? Should we close the issue or do we need to make changes to the existing mind map?

**Comment by winterrocks** [comment]
@tsteenbe o.k. to close? I'm o.k.
