### ISSUE TITLE
[CFP]: Building an OSPO around existing Open Source involvements 

### ISSUE THREAD

**Issue by jansche** [todogroup/ospology#216]
### Session Title

Disclaimer: This is not a session yet. It's a topic suggestion. I don't have to be the person to tell it. I'm currently involved in the exact topic and would love to share, but also learn from others.
https://dev.to/postman/how-postmans-building-their-open-source-program-office-ospo-hgf
 
"Building an OSPO around existing Open Source involvements"

### Session Description

Your company is already in the Open Source game? There's contributors and maintainers that get paid to do their job on an Open Source project? But there's a disconnect and unclarity why your company does this and on what terms contributing to Open Source is welcomed or permitted? 
Having an Open Source Program Office can be a solution. But there's challenges when you can't start from scratch, and there is already some sort of structure in place. Hear them in this real life story of creating the OSPO at Postman.

### Benefits to the Ecosystem

Learn about others' challenges along the road of creating an OSPO at your company. 
Handle existing relationships and structures, manage change.   

### Help us narrow down the focus a bit more. Please choose the OSPO related topic that best describes your proposal.

Adoption and Discovery, Becoming Strategic Decision-Making Partner

### What level of experience should the audience have to best understand your presentation?

OSPO 101 (Beginner)

### Speaker Name

Jan Schenk

### Speaker Bio

Program manager; tech community lover; Open Source advocate; Diversity, Equity, Inclusion and Belonging activist. I spent the majority of my life in the Tech Industry.

### Speaker preferred pronouns

He/They

**Comment by jansche** [comment]
Adding @floord (host/moderator) and @jlprat (panelist).

**Comment by anajsana** [comment]
Update on this: Panel Session scheduled for OSPOlogy January session 👍
