### ISSUE TITLE
[OSPO Book] Taxonomy: ways to improve book navigation and categorize references

### ISSUE THREAD

**Issue by anajsana** [todogroup/ospology#261]
Chapters cover a wide variety of topics which approach might change depending on the nature of the organization that has an OSPO (enterprises, NGO, government, university). 

An idea could be to make an initial segmentation and use them as tags that can be included in each chapter and/or topic. This way is easier for the reader to understand that a specific resource or study serves better organizations with "X" goals. For instance:

*This book is intended for Open Source Program Office managers, policymakers, executives, and stakeholders within organizations. Throughout the book, you can find up to three colored tags, that represent the different entities that could establish an open source program office (OSPO) based on the wide organization’s goals:*

* `Business Oriented` OSPOs are established within for-profit organizations, such as enterprises, that are primarily focused on creating business value through the use of open source software. These OSPOs may prioritize topics such as driving innovation, talent retention, legal compliance, or risk management.

* `Social Oriented`  These are OSPOs established within a government or public administrators that are focused on using open source software to achieve social or public policy objectives (e.g serving citizens). These OSPOs may prioritize topics such as interoperability, open data, accessibility, inclusion, privacy, security and transparency.

* `Educational Oriented` These are OSPOs established by educational institutions, such as universities or schools, that are focused on using open source software to support teaching, research and learning activities. These OSPOs may prioritize topics such as curriculum development, student engagement, open data, or knowledge sharing.

Maybe something to include in *Chapter 0*

**Comment by itprofjacobs** [comment]
I like this as  far as it goes, some thoughts…

Social Oriented: Might be split into civic/federal/governmental (pick one) and Humanitarian/Aid/other.  These distinctions are often important.  You’d either keep them both under the umbrella of “Social” or you might use them as individual categories.

Id use Education Oriented as the heading.  You might also note that there are business entities that provide training and certification (which are still education, but different than what “Higher Ed” does, and are definitely primarily focused on creating business value). That makes them different than purely educational entities that also do research, etc.

SJ

On Feb 22, 2023, at 12:11 PM, Ana Jimenez Santamaria ***@***.***> wrote:



Chapters cover a wide variety of topics which approach might change depending on the nature of the organization that has an OSPO (enterprises, NGO, government, university).

An idea could be to make an initial segmentation and use them as tags that can be included in each chapter and/or topic. This way is easier for the reader to understand that a specific resource or study serves better organizations with "X" goals. For instance:

This book is intended for Open Source Program Office managers, policymakers, executives, and stakeholders within organizations. Throughout the book, you can find up to three colored tags, that represent the different entities that could establish an open source program office (OSPO) based on the wide organization’s goals:

  *   Business Oriented OSPOs are established within for-profit organizations, such as enterprises, that are primarily focused on creating business value through the use of open source software. These OSPOs may prioritize topics such as driving innovation, talent retention, legal compliance, or risk management.

  *   Social Oriented These are OSPOs established within a government or public administrators that are focused on using open source software to achieve social or public policy objectives (e.g serving citizens). These OSPOs may prioritize topics such as interoperability, open data, accessibility, inclusion, privacy, security and transparency.

  *   Educational Oriented These are OSPOs established by educational institutions, such as universities or schools, that are focused on using open source software to support teaching, research and learning activities. These OSPOs may prioritize topics such as curriculum development, student engagement, open data, or knowledge sharing.

Maybe something to include in Chapter 0

**Comment by anajsana** [comment]
Thanks, @itprofjacobs for the valuable feedback!

> Social Oriented: Might be split into civic/federal/governmental (pick one) and Humanitarian/Aid/other

That's good idea and maybe those could be subsections of the main `social-oriented` tag

> You might also note that there are business entities that provide training and certification

Maybe having those as a "hybrid" special case (e.g `business-education`). Saying this, it might be helpful to have a schema that visualizes those "hybrid" OSPOs, that comes from the combination of the two. For instance:

![draw1](https://user-images.githubusercontent.com/43671777/220886347-d2f5f97e-d456-4cd4-8a97-a780d7e00ba4.png)

**Comment by itprofjacobs** [comment]
Good start.  I’m slammed this week and early next week, but I’ll add this to the stack to kick around some.

**Comment by chrisxie-fw** [comment]
How about this: 

An Open Source Program Office (OSPO) is a department within an organization that is responsible for managing the use, development, and release of open source software. The following are some categories of organizations that have OSPOs:

- Technology companies: Many technology companies, both large and small, have established OSPOs to manage their use and development of open source software. Examples of technology companies with OSPOs include Microsoft, Google, Facebook, Red Hat, and IBM.

- Government agencies: Some government agencies have established OSPOs to manage their use and development of open source software. Examples of government agencies with OSPOs include the United States Department of Defense, the European Commission, and the Government of India.

- Non-profit organizations: Many non-profit organizations, including foundations and advocacy groups, have established OSPOs to manage their use and development of open source software. Examples of non-profit organizations with OSPOs include the Linux Foundation, the Apache Software Foundation, and the Free Software Foundation.

- Educational institutions: Some universities and research institutions have established OSPOs to manage their use and development of open source software. Examples of educational institutions with OSPOs include the University of California, Berkeley and the Massachusetts Institute of Technology (MIT).

- Financial institutions: Some financial institutions have established OSPOs to manage their use and development of open source software. Examples of financial institutions with OSPOs include Goldman Sachs and JPMorgan Chase.

These categories are not mutually exclusive, and organizations from different sectors may have similar OSPOs.

**Comment by anajsana** [comment]
Thanks, @chrisxie-fw for your input! I think that, for naming categories, is important to focus on the goal type when categorizing OSPOs, rather than the industry (that is what you were suggesting). I think that within the "goal-type" categories, we can of course mention types of industries that can fit (so basically, the industries you have just mentioned: Technology companies, government agencies, etc). What about this:

| Goal-type |  Motivators | Industry Verticals |
| --- | --- | --- | 
| Business Oriented OSPOs | <li>Innovation</li><li>Risk Management</li><li>Legal Compliance</li><li>Talent Retention<li> | <li>Technology companies</li><li>Financial institutions</li>  |
| Educational Oriented OSPOs | <li>Knowledge Sharing</li><li>Student Engagement</li><li>Curriculum Development</li><li>Open Data<li> | Educational institutions  |

**Comment by itprofjacobs** [comment]
I like Ana’s first pass at visualization.  I feel like there’s some kind of Venn diagram, splatter plot or something that maps Goal, Motivators and institutions.  I’ll ask my team to take a look at this stuff over the next week and try to come up with some thoughts and perhaps a stab or two at a draft.

**Comment by anajsana** [comment]
FYI: related thread on taxonomy and book navigation: https://lists.todogroup.org/g/ospo-book-project/message/4

**Comment by anajsana** [comment]
The related PR that defines the taxonomy based on this issue discussion and contributors' feedback has been approved and merged: https://github.com/todogroup/ospology/blob/main/ospo-book/chapters/taxonomy.md

**Comment by anajsana** [comment]
To improve the description of each tag, please open a new PR with the edition of the taxonomy.md 👍 In addition, a glossary.md has been created and sent as PR for review: https://github.com/todogroup/ospology/pull/286

**Comment by anajsana** [comment]
Taxonomy already added to the OSPO Book: https://ospobook.todogroup.org/taxonomy/
