### ISSUE TITLE
[OSPO Book] Remove redundant glossary

### ISSUE THREAD

**Issue by cornelius** [todogroup/ospology#359]
The OSPO Book contains a  [glossary](https://github.com/todogroup/ospology/blob/main/ospo-book/content/en/glossary.md). Its content is mostly the same as the [OSPO Glossary](https://ospoglossary.todogroup.org/). I would suggest to remove the glossary from the book and point to the OSPO Glossary instead, so that there is no redundant content, which runs the risk of becoming inconsistent or outdated. The link in the header of the OSPO Book site could just link to https://ospoglossary.todogroup.org/.

**Comment by anajsana** [comment]
I'll work on it before our contributor call to get it fixed 👍

**Comment by anajsana** [comment]
This PR should solve the issue once it gets merged: https://github.com/todogroup/ospology/pull/453
