### ISSUE TITLE
[OSPO Book]: broken "Edit this page" link.

### ISSUE THREAD

**Issue by jfg956** [todogroup/ospology#383]
Hi,

When visiting the [OSPO Book Website](https://ospobook.todogroup.org/), there is an "Edit this page" link in the right sidebar.  This link leads to a non-existing page.

As an example, on the [home page of the OSPO Book](https://ospobook.todogroup.org/), the link points to {1a} while I think it should point to {1b} (missing `ospo-book` between `main` and `content`).

{1a}: https://github.com/todogroup/ospology/edit/main/content/en/_index.md
{1b}:  https://github.com/todogroup/ospology/edit/main/ospo-book/content/en/_index.md

Same problem on the [TOC page](https://ospobook.todogroup.org/toc/): {2a} while should be {2b}.

{2a}: https://github.com/todogroup/ospology/edit/main/content/en/toc.md
{2b}: https://github.com/todogroup/ospology/edit/main/ospo-book/content/en/toc.md

Thanks for looking into this,

Jean-François Gagné

**Comment by node** [comment]
Hi @jfg956  thanks for your feedback. 

I found the key point of this issue: 

We need to set this param in config.toml  at line  115 

```
# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = "ospo-book" 
```

**Comment by node** [comment]
It works now.

**Comment by cjyabraham** [comment]
The fix is deployed.

**Comment by jfg956** [comment]
Thanks Chris Yang for fixing this, and Chris Abraham for deploying the fix.
