### ISSUE TITLE
[OSPO Book]: linking to lf content inconsistent.

### ISSUE THREAD

**Issue by jfg956** [todogroup/ospology#393]
Hi,

in the OSPO Book, there are many links to Linux Foundation (lf) content.  But these are inconsistent, I found 3 patterns:
1. a link is to the lf website, example in {1},
2. a direct link to a pdf on the lf website, example in {2},
3. an external link to a pdf, example in {3}.

And about {2}, there is another way to link to that content in {4}.

I would suggest to always use the #1 pattern above, and I will submit a PR to fix #2 and #3.

Thanks, Jean-François Gagné

{1}: https://github.com/todogroup/ospology/blob/b53f3dd405b2be91458d029411bca2012c53b4c7/ospo-book/content/en/03-chapter.md?plain=1#L127
```
[the OSPO maturity model](https://linuxfoundation.org/tools/the-evolution-of-the-open-source-program-office-ospo/)
```

{2}: https://github.com/todogroup/ospology/blob/02f5e0098a6476909d7f5662f219a01e1939d928/ospo-book/content/en/02-chapter.md?plain=1#L38
```
[business value of the OSPO report](https://project.linuxfoundation.org/hubfs/LF%20Research/TODO%20Group%20-%20The%20Business%20Value%20of%20the%20OSPO%20-%20Report.pdf?hsLang=en)
```

{3}: https://github.com/todogroup/ospology/blob/02f5e0098a6476909d7f5662f219a01e1939d928/ospo-book/content/en/02-chapter.md?plain=1#L113
```
[This report by Dr. Ibrahim H](https://8112310.fs1.hubspotusercontent-na1.net/hubfs/8112310/LF%20Research/LF%20Research%20Guide%20to%20Enterprise%20Open%20Source.pdf)
```

{4}: https://github.com/todogroup/ospology/blob/739861eec72c8a581c3ce3e0d38e77bd2ce87b3a/ospo-book/content/en/references.md?plain=1#L68
```
[The Business Value of the OSPO](https://www.linuxfoundation.org/research/business-value-of-ospo)
```

**Comment by jfg956** [comment]
PR ready for review: https://github.com/todogroup/ospology/pull/394.

**Comment by node** [comment]
Review & merged, thanks for your feedback and PR .
