### ISSUE TITLE
ORT Community Days

### ISSUE THREAD

**Issue by nickvidal** [todogroup/ospology#416]
Would it be possible to share this event in the newsletter please:

ORT Community Days
6-7 March, 2024
Berlin, Germany
https://cd.oss-review-toolkit.org 

Thanks!

**Comment by anajsana** [comment]
Thank you @nickvidal! the upcoming newsletter will be sent next Tuesday, January 30th and I will review and work in the content in the upcoming weeks 👍 Happy to add it to the conference section once I prepare my PR, but if you would like to add it yourself, feel free to open a PR  in the md file and contribute to the newsletter. Also, if there is anything from OSI that might be interesting to OSPO, please don't hesitate to add it to the ICYMI article section: https://github.com/todogroup/ospology/blob/main/newsletter/2024-01-30.md

**Comment by nickvidal** [comment]
Thank you so much @anajsana! I just saw that @tsteenbe has created a PR #418
