### ISSUE TITLE
[OSPO Book] Chapter 4 - Section - Main text (including introduction)

### ISSUE THREAD

**Issue by alice-sowerby** [todogroup/ospology#473]
Content is being created in a markdown file https://github.com/todogroup/ospology/blob/main/ospo-book/content/en/04-chapter.md

**Comment by alice-sowerby** [comment]
@anajsana @todogroup/ospology-book-content I have reviewed this and it's ready for re-editing. Let me know if the suggestions are helpful and if you would like to chat more about it!

**Comment by anajsana** [comment]
Main text content from chapter 4 was already added, reviewed and merged using the new structure discussed in past calls: https://ospobook.todogroup.org/04-chapter/
