### ISSUE TITLE
[CFP]: Building an OSPO in the Energy Sector: The Alliander experiences

### ISSUE THREAD

**Issue by Jonasvdbo** [todogroup/ospology#51]
### Session Title

Building an OSPO in the Energy Sector: The Alliander experiences

### Session Description

Business sponsorship, enthusiasm and going for it. Those three ingredients define Alliander’s OSPO. After joining LF Energy and releasing our first open source project under the LF Energy umbrella, we started to recognize the need within Alliander for a group of people with the know-how and mandate to help bring structure and organization to the open source plans. And so some enthusiasts came together and discussed the various open source needs within the company. The OSPO turned out to be an excellent means for this because it created an overview of all open source activities. From there, we started consolidating knowledge, worked on building better open source development practices, familiarized the organization with innersource, improved license compliance, and looked for external opportunities for collaborating via open source. The OSPO as a strategic pillar for change was born. Two years later, here we are. We have released and contributed to many more open source projects, have a functioning Open Source Program Office and are starting to embed the open source mindset in the organization.

In this session, we will tell you more about our OSPO journey, our OSPO ambitions and will be introducing LF Energy. 

### Benefits to the Ecosystem

Learn about Alliander's experiences in building an OSPO in the Energy Sector. 

### Help us narrow down the focus a bit more. Please choose the OSPO related topic that best describes your proposal.

Adoption and Discovery

### What level of experience should the audience have to best understand your presentation?

OSPO 101 (Beginner)

### Speaker Name

Jonas van den Bogaard & Nico Rikken

### Speaker Bio

Jonas van den Bogaard is solution architect & open source evangelist at Alliander. Alliander is the largest DSO in the Netherlands. As a DSO, Alliander is responsible for the distribution of energy such as electricity, gas and heat.

Nico Rikken is Senoir DevOps Consultant & open source evangelist at Alliander. Alliander is the largest DSO in the Netherlands. As a DSO, Alliander is responsible for the distribution of energy such as electricity, gas and heat.

### Speaker preferred pronouns

Please add your preferred pronouns, if any (e.g She/ Her, They/ Them)

**Comment by caniszczyk** [comment]
Looks awesome, love it!

**Comment by caniszczyk** [comment]
+1

**Comment by anajsana** [comment]
FYI: the event has been created and scheduled for March 2nd at 5:00 pm CET. RSVP is open :) 

https://community.linuxfoundation.org/events/details/lfhq-todo-group-presents-building-an-ospo-in-the-energy-sector-the-alliander-experiences/
