### ISSUE TITLE
[CFP]: How Academic OSPOs Are Amplifying Research Impact … and How Industry OSPOs Can Benefit Please provide more details about your proposal

### ISSUE THREAD

**Issue by slieggi** [todogroup/ospology#54]
### Session Title

How Academic OSPOs Are Amplifying Research Impact … and How Industry OSPOs Can Benefit
Please provide more details about your proposal

### Session Description

OSPOs in academia need to be in alignment with the missions of universities, including teaching, research, and public service. These missions are very different from the missions of industrial corporations. But the strategic goals of both academic and industry OSPOs are complementary and enable acceleration of innovation that benefits all stakeholders. In this presentation we will provide an overview of the efforts being made at UC Santa Cruz to amplify the impact of academic research by leveraging open source ecosystems, and how these activities are opening opportunities that can benefit  industry partners – both through the engagement with university researchers and the education of the next generation of technical professionals. 

### Benefits to the Ecosystem

The audience will learn about:
- Efforts to support academic research based in open source ecosystems that align with industry practices;
- Development of innovative curricula and mentoring programs that teach open source techniques to the next generation of technical professionals; and 
- How industry OSPOs and the wider open source community can support these efforts and benefit from their outcomes.

### Help us narrow down the focus a bit more. Please choose the OSPO related topic that best describes your proposal.

Evangelizing OSS Use and Ecosystem Participation, Hosting OSS Projects and Growing Communities

### Speaker Name

Carlos Maltzahn and Stephanie Lieggi

### Speaker Bio

Carlos Maltzahn is the founding director for the Center for Research in Open Source Software (cross.ucsc.edu) and the new UC Santa Cruz OSPO. He is an Adjunct Professor of Computer Science & Engineering at UC Santa Cruz, a co-founder of the Ceph open source distributed storage system project, and co-founded the Systems Research Lab, known for its cutting-edge work on programmable storage systems, big data storage & processing, scalable data management, distributed system performance management, and practical reproducible evaluation of computer systems. Prior to joining UCSC, he was a Performance Engineer, Netapp.  (see people.ucsc.edu/carlosm)

Stephanie Lieggi is assistant director for CROSS and the UC Santa Cruz OSPO. In her current roles she supports the work of academic-based open source projects and enables a sustainable contributor base through the establishment of hands-on mentorship programs. Stephanie promotes the use of open source in academic settings as well as increasing diversity and inclusion in open source ecosystems. Prior to joining UCSC, she was a Senior Research Associate and Adjunct Professor at the Center for Nonproliferation Studies (CNS) at the Middlebury Institute of International Studies at Monterey (MIIS). 

### Speaker preferred pronouns

Carlos Maltzahn (he, him)
Stephanie Lieggi (she, her)

**Comment by anajsana** [comment]
Thanks a lot @slieggi! this topic looks great to schedule for the April OSPOlogy session (cc @caniszczyk )

**Comment by anajsana** [comment]
@slieggi I have scheduled and published the session for April, Wed 6th. RSVP is already open: https://community.linuxfoundation.org/events/details/lfhq-todo-group-presents-how-academic-ospos-are-amplifying-research-impact/

Please let me know if you'd like to change anything from your bio or topic description 🙂
