### ISSUE TITLE
[CFP]: 3rd Party Outbound OSPO: An extrospective approach to OSS

### ISSUE THREAD

**Issue by jlprat** [todogroup/ospology#64]
### Session Title

3rd Party Outbound OSPO: An extrospective approach to OSS

### Session Description

An entire department, working in the open, focusing on other companies’ Open Source repositories… sounds like something unthinkable, right? Well… except is not, and I’m here to tell you the story of the OSPO team at Aiven, whose main mission is to contribute and guarantee the sustainability of external OSS projects.

The most common and widespread way to support OSS communities takes the form of donations. Money donations are a good way to secure projects financially, however, you can rarely foresee their impact on the community. On top of that, in some cases, money is just a palliative, and will not prevent contributors with a day to day job from burning out. We think an alternative exists, where, instead of money, companies donate employees' time to directly work on existing critical OSS projects.

Learn from Aiven’s experience building their OSPO, and how it impacts mission, scope, hiring, team composition, and metrics definitions.

We will share the benefits that the company is experiencing as well as direct examples of how our OSPO is improving the sustainability of various OSS communities. But the roads of our project were seldom perfect, and we'll discuss pitfalls and areas to watch out for, so you know them in advance when building your own Outbound OSPO focusing on 3rd party OSS.

### Benefits to the Ecosystem

You will learn:
* an Innovative way of doing OSPOs
* when it’s good and when it’s not
* how it can improve the global OSS ecosystem
* how to measure success
* how recruiting changes
* how fragile OSS communities and projects can benefit from more companies adopting the new approach

### Help us narrow down the focus a bit more. Please choose the OSPO related topic that best describes your proposal.

Adoption and Discovery, Evangelizing OSS Use and Ecosystem Participation

### What level of experience should the audience have to best understand your presentation?

OSPO 101 (Beginner)

### Speaker Name

Josep Prat

### Speaker Bio

Josep Prat is a Open Source Software Manager at Aiven and is passionate about Open Source Technologies. With a strong background in Scala and distributed systems, he contributes to several Open Source Projects like Kafka and Akka, and is a committer for Akka HTTP. In his spare time, Josep enjoys late and long brunches on Sundays, kids permitting.

### Speaker preferred pronouns

He/Him

**Comment by anajsana** [comment]
LGMT 👍 Thanks for this submission!

**Comment by anajsana** [comment]
Landing page for this OSPOlogy session has been created for Wed, May 11th: https://community.linuxfoundation.org/events/details/lfhq-todo-group-presents-3rd-party-outbound-ospo-an-extrospective-approach-to-oss/

Thank you so much!
