### ISSUE TITLE
Refine readme

### ISSUE THREAD

**Issue by sdake** [todogroup/ospology#81]
The top level readme is a little difficult to read.

Specifically
- switch communication to active voice
- improve the organization of sections.
- remove conjunctions.
- add emojis to look hip!

**Comment by sdake** [comment]
PR with my take: https://github.com/todogroup/ospology/pull/80

Rendering is here: https://github.com/sdake/ospology/tree/refine/readme

**Comment by anajsana** [comment]
Thanks a lot for your contributions @sdake ! I've added some comments to your PRs 🙂

**Comment by anajsana** [comment]
PRs are merged and we can close this task!
