### ISSUE TITLE
Migrate text2mm to markmap for OSPO Mind Map

### ISSUE THREAD

**Issue by anajsana** [todogroup/ospology#83]
Based on a [previous discussion](https://github.com/todogroup/ospology/issues/78#issuecomment-1086666041) to render SVG/PNG/PDF with tooling instead of uploading a text file to the repo, we have considered migrating to `markmap` to continue to build the OSPO mindmap.

**Action Items**

- Create `ospomindmap.md` and change it for [OSPO_Mind_Map.txt](https://github.com/todogroup/ospology/blob/main/ospo-mindmap/Content/OSPO_Mind_Map.txt) via PR
- Update documentation (https://markmap.js.org/docs#what-is-markmap) and submitt PR

**Comment by byjrack** [comment]
@anajsana I haven't played with it much yet in Github context, but Github has added some mermaid support which might meet your needs.  Only gap off the top of my head is exporting the rendered content easily which might be critical path.

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by anajsana** [comment]
> @anajsana I haven't played with it much yet in Github context, but Github has added some mermaid support which might meet your needs. Only gap off the top of my head is exporting the rendered content easily which might be critical path.
> 
> https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Thanks for taking a look to this and share this idea @byjrack 🤩 mermaid was indeed mentioned by @jsmanrique in the OSPO Forum Discussion prior creating the ospo mind map folder. Unfortunately,  I only found diagram support (there is no mind map markdown integration at this point)

Markmap has a MIT license, works with makdown and has cli and VSCode integration to export data into html and svg file. 

FyI, I've already added the `md` file and built a site with the generated html to see the interactive mindmap on a public website (working with the DNS to try this to point to ospomindmap.todogroup.org)

https://ospomindmap.netlify.app/

**Comment by byjrack** [comment]
Yeah I have just most of my mind maps using diagram software myself, but yeah if there is a specific structure you were trying to create than yeah mermaid def won't be the best option there.

**Comment by anajsana** [comment]
This task is already done. Closing this issue!
